### ISSUE TITLE
Random number generated

### ISSUE THREAD

**Issue by marioiordanov** [artichoke/rand_mt#192]
I have a code in python that uses the random.py file Random class. In python when generating numbers with the Random class and seed 123 I receive a number 261662301160200998434711212977610535782, but when I try to reproduce the same in Rust it gives me this result 258431468044781239883754362733579478088.
Code example:

```rust
let mut rng = mt::MT19937::MT19937::from_seed(123i32.to_le_bytes());
let mut bytes:[u8;16] = [0;16]; 
let res:u128 = rng.gen();
```

Can you help solve this issue

**Comment by lopopolo** [comment]
Calling `Mt19937GenRand32::from_seed` with an `i32` number ends up converting that number to a `u32`. The code you have is equivalent to this:

```rust
let seed = u32::from_le_bytes(123_i32.to_le_bytes());
let mut rng = Mt19937GenRand32::new(seed);
let res: u128 = rng.gen();
```

Additionally, `rand_mt` doesn't guarantee compatibility with CPython's `Random` class. It only guarantees compatibility with CRuby's `Random` class.

**Comment by lopopolo** [comment]
Closing as invalid. If you can reproduce this situation by demonstrating a difference in behavior with CRuby, please re-open.
